# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Create HTML site
# Includes building automatically when either of the relavent JSON files update on the main branch or on the push of a button
on: 
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2
    - name: create HTML file
      run: |
        python create_tool_landing_page.py
        python create_catalog_landing_page.py Browse_config.json
        # note that static images and FIMS landing page (index.html) are
        # already in the deploy folder.
        # for now, don't create individual drawer pages
    - name: upload
      uses: actions/upload-artifact@v3
      with: 
        path: deploy
        name: deploy
