# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Create HTML site
# Includes building automatically when either of the relavent JSON files update on the main branch or on the push of a button
on: 
  workflow_dispatch:
  push:

permissions: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2
        pip install requests
    - name: create HTML file
      run: |
        python create_tool_landing_page.py dev_config.json
        python create_catalog_landing_page.py dev_config.json
        python create_site_index_page.py dev_config.json
    - name: upload
      uses: actions/upload-artifact@v4
      with: 
        path: deploy
        name: deploy
