# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: create html PS
# Includes building automatically when either of the relavent JSON files update on the main branch or on the push of a button
on: 
  workflow_dispatch:
  push:
    paths:
      - 'ProSpec_config.json'
      - 'model_list_dir/**.json'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2
    - name: create HTML
      run: |
        python create_html_from_jsonmodellist.py ProSpec_config.json
    - name: Pushes file to repo branch
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'html/index.html'
        destination_repo: 'NMFS-Protected-Species-Tools/nmfs-protected-species-tools.github.io'
        destination_folder: '.'
        user_email: 'kathryn.doering@noaa.gov'
        user_name: 'k-doering-NOAA'
        commit_message: 'Update PR index.html'
        destination_branch: 'new_html_page_2'
    - name: 'Create Pull Request'
      uses: actions/github-script@v6
      with:
          github-token: ${{ secrets.API_TOKEN_GITHUB }}
          script: |
              github.rest.pulls.create({owner: 'NMFS-Protected-Species-Tools', 
                                      repo: 'nmfs-protected-species-tools.github.io',
                                      title: 'Changes to html',
                                      head: 'new_html_page_2', 
                                      base: 'master'});
                                      
