# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Create and Deploy Dev HTMl site
# Includes building automatically when either of the relavent JSON files update on the main branch or on the push of a button
on: 
  workflow_dispatch:
#  push:
#    branches: 
#      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2
        pip install requests
    - name: create HTML file
      run: |
        python create_tool_landing_page.py dev_config.json
        python create_catalog_landing_page.py dev_config.json
        python create_site_index_page.py dev_config.json
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: deploy # The folder the action should deploy.
        repository-name: noaa-fisheries-integrated-toolbox/fit-dev
        token: ${{ secrets.API_TOKEN_GITHUB }}