name: Validate config JSONs

on:
  workflow_dispatch:
  push:

permissions: {}

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Validate JSON, prod and dev config
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: schema_config.json
          INPUT_JSONS: prod_config.json,dev_config.json
      - name: Validate JSON, models_all
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: schema_models_all.json
          INPUT_JSONS: models_all.json
          
          